name: dity
# dity is Yunshu version, with per token conditioning. It doesn't help or hurt on reg. diffusion,
# but could help on paths that are not all noised the same. Must test w/ e.g. nll_roar training
# and dity versus dit. But it generalizes better to ROAR metric (even trained on diffusion) which
# is a strong sign this actually works!
dim_h: 768
n_blocks: 12
n_heads: 12
cond_dim: 128
dropout: 0.1
dit_cond: true
dit_attn_bias: false

# For text8, on a6000, peak micro batch for this model is 40.