checkpoint_every_epoch:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  save_top_k: -1  # 不保存"最佳"模型
  save_last: True  # 将最后一个模型保存为 ${save_dir}/checkpoints/last_epoch.ckpt
  filename: 'epoch-{epoch}'  # 每个 epoch 检查点的命名格式
  dirpath: ${checkpointing.save_dir}/checkpoints
  verbose: True
  auto_insert_metric_name: False
  every_n_epochs: 1  # 每 1 个 epoch 保存一次
  save_on_train_epoch_end: True  # 在每个训练 epoch 结束时保存