# configs/config.yaml
defaults:
  - data: owt
  - backbone: dit-sahoo
  - convert: softmaxbias
  - optim: adamw  # adamw | sgd
  - optim/scheduler: none
  - train: base-owt
  - eval: base
  - snrpath: lognormal-owt
  - _self_

# global settings
logging:
  enabled: true          # turn logging on/off
  project: dsl2          # custom project name
  entity: dsl2-gv        # optional, your wandb username/team
  log_every: 20
  show_speed: true

device: null  # "cpu" | "mps" | "cuda"  # override
seed: 1
run:
  workdir: ${hydra:runtime.output_dir}  # hydra output dir

# hydra runtime
hydra:
  run:
    dir: ${oc.env:HYDRA_RUN_DIR,/tmp/outputs}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
