defaults:
  - _self_
  - /callbacks: [checkpoint_every_n_steps, checkpoint_monitor, learning_rate_monitor, checkpoint_every_epoch]
  - /data: text8 # openwebtext
  - /model: small
  - /strategy: ddp
  - /noise: loglinear
  - /lr_scheduler: constant_warmup

mode: train  # train / ppl_eval / sample_eval
diffusion: absorbing_state # Yunshu: no idea why this is needed
backbone: dit  # dit / dimamba / ar
parameterization: subs  # subs / d3pm / sedd      # Yunshu: I don't think I need this
time_conditioning: False # Yunshu: no idea what is this
T: 0  # 0 (continuous time) / 1000 # Yunshu: seems to be max noise-level in their discrete diffusion repo
subs_masking: False # Yunshu: d3pm related stuff

seed: 1

loader:
  global_batch_size: 512
  eval_global_batch_size: ${.global_batch_size}
  # Note: batch_size and eval_batch_size are **per machine**
  batch_size: ${div_up:${.global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  eval_batch_size: ${div_up:${.eval_global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  # num_workers: ${eval:"len(__import__('os').sched_getaffinity(0))"}
  num_workers: ${eval:"min(2, len(__import__('os').sched_getaffinity(0)) // 2)"}
  pin_memory: True

# Yunshu: the following sampler is used during training, mainly to check the generative perplexity
# also used in sampling phase, generating text samples
# Be careful when I reimplement the DSL class, only include those who are needed
sampling:
  predictor: ddpm_cache  # analytic, ddpm, ddpm_cache
  steps: 128
  noise_removal: True
  # TODO(yair): @subham, why aren't these params under `eval`?
  num_sample_batches: 2  # Total samples: `num_gpus` * `loader.eval_batch_size` * num_sample_batches
  num_sample_log: 2
  semi_ar: False
  stride_length: 1
  num_strides: 1
  sampling_method: null

training:
  ema: 0.9999
  sampling_eps: 1e-3 
  # Yunshu: the following three are not very needed for DSL
  antithetic_sampling: True
  importance_sampling: False
  change_of_variables: False
  # DSL specific setting
  t_max: 10.
  val_mse_plot: True # plot MSE plot during validation
  reconst_weight: 1.

# Yunshu: mainly related to calculate the PPL
# So need to be implemented. 
eval:
  checkpoint_path: ''  # Used to evaluate a checkpoint after training.
  disable_ema: False
  compute_generative_perplexity: False
  perplexity_batch_size: 8
  compute_perplexity_on_sanity: False
  gen_ppl_eval_model_name_or_path: gpt2-large  # gpt2-large, meta-llama/Llama-2-7b-hf
  generate_samples: True

optim:
  weight_decay: 0
  lr: 3e-4 # 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8

trainer:
  _target_: lightning.Trainer
  accelerator: cuda
  num_nodes: 1
  devices: ${device_count:}
  accumulate_grad_batches: ${div_up:${loader.global_batch_size}, ${eval:${trainer.devices} * ${loader.batch_size} * ${trainer.num_nodes}}}
  gradient_clip_val: 1.0
  precision: 'bf16'
  num_sanity_val_steps: 2
  max_steps: 1_000_000 # Yunshu: only train for max_steps, each step is a gradient update, one batch of data is trained
  log_every_n_steps: 10
  limit_train_batches: 1.0   # train on full dataset, can be used to toggle quick run
  limit_val_batches: 1.0     # validate on full dataset, can be used to toggle quick run
  val_check_interval: 1.0 # 10000

wandb:
  project: text-diffusion
  notes: Mulan for text
  group: null
  job_type: null
  name: null
  id: ${.name}_${seed}_${now:%H%M%S}
  tags:
    - ${noise.type}
    - ${data.train}
    - ${data.valid}

hydra:
  run:
    dir: ./outputs/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  job:
    chdir: true

checkpointing:
  # Use custom `save_dir` if, e.g., saving to S3 bucket, otherwise leave this parameter as is
  save_dir: ${cwd:}
  # Note: `checkpoints` path should correspond to `checkpoint_every_n_steps.dirpath`
  resume_from_ckpt: true
  resume_ckpt_path: ${.save_dir}/checkpoints/last.ckpt
