max_steps: 10000
resume: null

# lm1b options
batch_size: 128  # 112 for lm1b on 4090, memory limit. Still 4090 is slightly faster than a6000!
eval_batch_size: 128  #  416 on 4090
grad_accum_steps: 1

num_workers: 4
pin_memory: true
drop_last: true
shuffle: true
mix_lambda: 0.  # lambda * NLL ROAR + (1-lambda) * CE
num_nodes: 1  # no multi-node for now

init_pretrained: false
pretrained_model: 'kuleshov-group/mdlm-owt'

ckpt:
  dir: ${hydra:run.dir}/checkpoints
  save_every: null       # set to 0 or null to disable periodic saves
  save_last: true
  save_best: true

val:
  enabled: true
  every: 200
  max_batches: 5     # optional cap on #val batches per eval (int or null)