# Options used by eval.py only. Val during training is done more cheaply
ckpt: null   # path to a checkpoint file

nll_metrics: false
sampling_metrics: true
max_batches: null
interactive: false  # if true, step in to an ipython shell after loading model

nll_n_rep: 5  # Estimator may be biased if too low.
roar_n_rep: 1
nll_int_steps: 50  # steps for integral, more is better but slower
use_pretrained: false  # Can revert to pretrained weights for comparison