name: small
type: ddit # not sure where is this term used
dim_h: 768 # hidden dimension for transformers
# DSL related parts
dim_embed: 16 # token embedding dimension; NOTE Yunshu: how to determine this value?
dit_cond: True # conditioning on y
dit_attn_bias: False
logvar_predictor_dim: 64 # NOTE: don't know how to figure out this
# Transformer parts
cond_dim: 128
mlp_size: 128 # BERT only, for MLP embedding magnitude
length: 256 # 1024 # should be how long to generate when compute generative perplexity
n_blocks: 12
n_heads: 12
scale_by_sigma: True # seems not useful in DSL setting
dropout: 0.1
tie_word_embeddings: False
